### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by anton164** [cartant/rxjs-spy-devtools#4]
Hey @cartant,

I would love to see something like this for RxJS, since we've embraced RxJS pretty extensively at Ardoq and are using it for state management, side effects, etc.

I was wondering if you have any ideas on how I could start contributing to the project? Perhaps even jumping on a call might be the best :-) 

Also, I haven't actually been able to build the extension from the master branch.

On step 4 I get:
```
ERROR in /Users/anton164/git/rxjs-spy-devtools/extension/source/background.ts
[tsl] ERROR in /Users/anton164/git/rxjs-spy-devtools/extension/source/background.ts(86,12)
      TS2345: Argument of type '(port: Port) => boolean | undefined' is not assignable to parameter of type '(value: Port, index: number) => boolean'.
  Type 'boolean | undefined' is not assignable to type 'boolean'.
    Type 'undefined' is not assignable to type 'boolean'.

ERROR in /Users/anton164/git/rxjs-spy-devtools/extension/source/background.ts
[tsl] ERROR in /Users/anton164/git/rxjs-spy-devtools/extension/source/background.ts(87,30)
      TS2339: Property 'sender' does not exist on type '{}'.

ERROR in /Users/anton164/git/rxjs-spy-devtools/extension/source/background.ts
[tsl] ERROR in /Users/anton164/git/rxjs-spy-devtools/extension/source/background.ts(91,13)
      TS2322: Type '{}' is not assignable to type 'Port'.

ERROR in /Users/anton164/git/rxjs-spy-devtools/extension/source/background.ts
[tsl] ERROR in /Users/anton164/git/rxjs-spy-devtools/extension/source/background.ts(93,34)
      TS2322: Type '{}' is not assignable to type 'Port'.

ERROR in /Users/anton164/git/rxjs-spy-devtools/extension/source/background.ts
[tsl] ERROR in /Users/anton164/git/rxjs-spy-devtools/extension/source/background.ts(96,42)
      TS2345: Argument of type '{}' is not assignable to parameter of type 'Port'.
  Property 'postMessage' is missing in type '{}'.

ERROR in /Users/anton164/git/rxjs-spy-devtools/extension/source/background.ts
[tsl] ERROR in /Users/anton164/git/rxjs-spy-devtools/extension/source/background.ts(107,24)
      TS2339: Property 'postType' does not exist on type '{}'.
```

**Comment by cartant** [comment]
I should archive this repo, as I've moved development elsewhere.

I started reworking `rxjs-spy` at the end of last year. I've finished that and I'm now adding the DevTools - both are in the one mono repo. ATM, the repo is private, but it will be made public before the extension is published, etc.

From the errors, it looks like the typings for Chrome have changed. Unfortunately, I don't have the time to look into it, ATM.

Anyway, there were numerous parts of the implementation in this repo that were problematic. These have been addressed and new features have been added.

**Comment by anton164** [comment]
I see, would it be possible to get access somehow to help with testing, possibly development? :) 

My e-mail is anton at ardoq dot com. We are in the process of adopting `rxjs-spy` so would make sense if we could go with the rewritten version straight away (and hopefully it can give you some useful "battle-testing" as well :)) .

**Comment by anton164** [comment]
Hey, any update on this? :) 

If you think it'll just create more overhead for you I might go ahead and fork this repo, but seems like that might be a waste if you're rewriting both this and Rxjs-spy?

**Comment by cartant** [comment]
It won't be made available until the DevTools panel is at least in place and functional. That's the last piece and I'm working on it ATM.

**Comment by anton164** [comment]
Fair enough, good luck - looking forward to it!

**Comment by anton164** [comment]
@cartant Any rough idea of when you might publish an initial version of RXJS devtools?

**Comment by cartant** [comment]
@anton164 [about 6 to 8 weeks](https://meta.stackexchange.com/a/19514/338149) ... but probably less.
