### ISSUE TITLE
extension build error

### ISSUE THREAD

**Issue by bifty** [cartant/rxjs-spy-devtools#5]
gives a:

rxjs-spy-devtools\extension\source\background.ts(86,12)
      TS2345: Argument of type '(port: Port) => boolean | undefined' is not assignable to parameter of type '(value: Port, index: number) => boolean'.
  Type 'boolean | undefined' is not assignable to type 'boolean'.
    Type 'undefined' is not assignable to type 'boolean'.

**Comment by cartant** [comment]
It's because the Chrome typings have been changed. This project was an experiment that has been set aside for a better RxJS DevTools implementation - with more features - that I am currently working on. I will most likely archive this project.
